services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  zenml:
    image: zenmldocker/zenml-server
    container_name: zenml
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      ZENML_STORE_URL: mysql://root:password@host.docker.internal/zenml
    links:
      - mysql
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge