services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  zenml:
    image: zenmldocker/zenml-server
    container_name: zenml
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      ZENML_STORE_URL: mysql://root:password@host.docker.internal/zenml
    links:
      - mysql
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - app_network
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT_LOG_LEVEL: INFO

volumes:
  mysql_data:
  qdrant_data:

networks:
  app_network:
    driver: bridge